apiVersion: apps/v1
kind: Deployment
metadata:
  name: JenkinsIntegration-k8s
  labels:
    app: JenkinsIntegration-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: JenkinsIntegration-k8s
  template:
    metadata:
      labels:
        app: JenkinsIntegration-k8s
    spec:
      containers:
      - name: JenkinsIntegration-k8s-container
        image: kowsylakshu/jenkinsintegration:latest
        ports:
        -containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: JenkinsIntegration-k8s
spec:
  type: NodePort
  ports: 
    - port: 80
      targetPort: 8080
  selector:
    app: JenkinsIntegration-k8s
    
